### ISSUE TITLE
Blinking

### ISSUE THREAD

**Issue by jcv-** [atom0s/Wardrobe#6]
First off, thanks for this application.

Second, I'm using 5.0.4 and seem to be blinking randomly when running and interacting with NPCs. Please let me know if there is any other information that I can provide.

**Comment by atom0s** [comment]
This is not a bug and has been in Wardrobe since it was released. It is due to how the memory is written to by the game when specific packets are handled. When you interact with an npc the game attempts to force-refresh your character. The same thing happens with various other events such as obtaining items etc. I opt'd to not patch any part of the game to keep Wardrobe as ToS friendly as possible.
